on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.0
    strategy:
      fail-fast: false
      matrix:
        board: [nice_nano_v2]
        shield: [my_mouse]
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-zmk-modules-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-zmk-modules-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build
        run: west build -d build/${{ matrix.board }}/${{ matrix.shield }} -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}-${{ matrix.shield }}
          path: build/${{ matrix.board }}/${{ matrix.shield }}/zephyr/zmk.uf2
